<script setup>
import { computed } from 'vue';
import Tooltip from './common/Tooltip.vue';

const props = defineProps({
  overview: {
    type: Object,
    default: () => ({})
  }
});

const cacheEfficiencyBadge = computed(() => {
  const rate = props.overview?.cacheHitRate ?? 0;
  if (rate >= 80) return { type: 'green', label: '🔥 High Efficiency' };
  if (rate >= 50) return { type: 'blue', label: '⚡ Moderate Cache' };
  return { type: 'yellow', label: '⚠️ Low Cache Hit' };
});
</script>

<template>
  <div class="metrics-grid grid-4">
    <!-- Card 1: Total Tokens -->
    <div class="metric-card card">
      <div class="metric-head">
        <span class="metric-title">Total Tokens</span>
        <Tooltip 
          title="Total Lifetime Tokens" 
          text="The combined sum of all input, cached, reasoning, and output tokens across your recorded sessions." 
          why-it-matters="Gives you a high-level view of your overall token volume."
        />
      </div>
      <div class="metric-main">
        <span class="metric-value mono">
          {{ (overview?.totalTokens || 0).toLocaleString() }}
        </span>
      </div>
      <div class="metric-footer">
        <span class="sub-stat">
          <strong class="mono">{{ overview?.totalSessions || 0 }}</strong> total sessions
        </span>
      </div>
    </div>

    <!-- Card 2: Cache Hit Rate -->
    <div class="metric-card card">
      <div class="metric-head">
        <span class="metric-title">Cache Hit Rate</span>
        <Tooltip 
          title="Prompt Cache Hit Rate" 
          text="The percentage of prompt inputs that were served directly from OpenAI's memory cache." 
          why-it-matters="Cached tokens are processed up to 80% cheaper and much faster than fresh input tokens."
        />
      </div>
      <div class="metric-main">
        <span class="metric-value mono text-blue">
          {{ overview?.cacheHitRate || 0 }}%
        </span>
      </div>
      <div class="metric-footer">
        <span :class="['badge', `badge-${cacheEfficiencyBadge.type}`]">
          {{ cacheEfficiencyBadge.label }}
        </span>
      </div>
    </div>

    <!-- Card 3: Reasoning Tokens -->
    <div class="metric-card card">
      <div class="metric-head">
        <span class="metric-title">Reasoning Tokens</span>
        <Tooltip 
          title="Internal Thinking Tokens" 
          text="Tokens generated by reasoning models (like o3-mini) during their internal deliberation phase before acting or responding." 
          why-it-matters="Crucial for difficult coding problems, but wasteful if spent on simple formatting or chore tasks."
        />
      </div>
      <div class="metric-main">
        <span class="metric-value mono text-purple">
          {{ (overview?.totalReasoning || 0).toLocaleString() }}
        </span>
      </div>
      <div class="metric-footer">
        <span class="sub-stat text-dim">
          Model Thinking Effort
        </span>
      </div>
    </div>

    <!-- Card 4: Estimated Savings -->
    <div class="metric-card card">
      <div class="metric-head">
        <span class="metric-title">Estimated $ Saved</span>
        <Tooltip 
          title="Cost Savings from Caching" 
          text="Estimated financial savings gained from OpenAI's prompt caching discounts compared to raw full-price input." 
          why-it-matters="Shows the direct financial ROI of keeping prompt prefixes stable and modular."
        />
      </div>
      <div class="metric-main">
        <span class="metric-value mono text-green">
          ${{ overview?.estimatedSavingsDollars || '0.00' }}
        </span>
      </div>
      <div class="metric-footer">
        <span class="sub-stat text-green">
          💰 Saved via prompt cache
        </span>
      </div>
    </div>
  </div>
</template>

<style scoped>
.metrics-grid {
  margin-bottom: 24px;
}

.metric-card {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}

.metric-head {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}

.metric-title {
  font-size: 0.82rem;
  font-weight: 600;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.metric-main {
  margin-bottom: 14px;
}

.metric-value {
  font-size: 1.65rem;
  font-weight: 800;
}

.metric-footer {
  display: flex;
  align-items: center;
  font-size: 0.78rem;
  color: var(--text-muted);
}

.text-blue { color: var(--accent-blue); }
.text-purple { color: var(--accent-purple); }
.text-green { color: var(--accent-green); }
</style>
